Repository Great-Hill-Corporation/trueblocks-docker, pull requests merged in 2019-07, with the labels that each got.

#86 Improve routes in line with new template parser
  .gitignore
  api/docs/index.html
  api/server.generated.js
  template-parser/components/templateHandlers.js
  template-parser/components/warnings.js
  template-parser/output/apiary.generated.apib
  template-parser/output/docs.html
  template-parser/output/server.generated.js
  template-parser/routeToToolMap.json
  templates/apiary.template.apib
  templates/server.template.js
Labels: in progress

#93 Fixes #92
  template-parser/.gitignore
  template-parser/get-options.sh
  template-parser/misc/example.csv
  template-parser/misc/exampleInput.txt
Labels: needs review

#98 API cleanup
  Dockerfile
  api/package.json
  api/server.js
  template-parser/README.md
  template-parser/components/inputParser.js
  template-parser/components/templateHandlers.js
  template-parser/index.js
  template-parser/misc/example.csv
  template-parser/package-lock.json
  template-parser/package.json
  template-parser/routeToToolMap.json
  templates/server.template.js
  trueblocks.entrypoint.sh
Labels: needs review

#103 cleanup docs headings
  template-parser/components/templateHandlers.js
  template-parser/misc/example.csv
  templates/apiary.template.apib
Labels: invalid
